spring:
  datasource:
    url: jdbc:h2:mem:codequest
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

server:
  port: 8080
