spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/codequest
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true

# JWT Configuration (86400000 = 24 heures)
codequest.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
codequest.app.jwtExpirationMs=86400000
