spring.application.name=codequest
server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/codequest}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=false

# JWT Configuration (86400000 = 24 heures)
codequest.app.jwtSecret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
codequest.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}

# CORS Configuration
codequest.app.corsOrigins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://*.pages.dev,https://*.onrender.com}
